#!/usr/bin/env bash

echo "*** PHP CS FIXER ***"
CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.php')
if \[ -n "$CHANGED_FILES" \]; then
    docker compose exec -it php vendor/bin/php-cs-fixer fix $CHANGED_FILES;
fi

echo "*** PHPSTAN ***"
docker compose exec -it php vendor/bin/phpstan --memory-limit=-1 analyse main.php
if [ $? -ne 0 ]; then
  printf "\n\t\033[1;31m[PHPStan] Commit Aborted\n\n\033[0m"
  exit 2
fi

