# Use the official MySQL image as the base
FROM mysql:8.0

# Set environment variables for MySQL
ENV MYSQL_DATABASE=app
ENV MYSQL_ROOT_PASSWORD=root

# Define a volume that points to the MySQL data directory
VOLUME /var/lib/mysql

# Expose the MySQL port
EXPOSE 3306
